.TH git-annex-transferkeys 1
.SH NAME
git-annex-transferkeys \- transfers keys (deprecated)
.PP
.SH SYNOPSIS
git annex transferkeys
.PP
.SH DESCRIPTION
This plumbing\-level command is used to transfer data, by the assistant
in git-annex version 8.20201127 and older. It is still included only
to prevent breakage during upgrades.
.PP
It is a long\-running process, which is fed instructions about the keys
to transfer using an internal stdio protocol, which is
intentionally not documented (as it may change at any time).
.PP
.SH OPTIONS
.IP "The git-annex\-common\-options(1) can be used."
.IP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

