.TH git-annex-trust 1
.SH NAME
git-annex-trust \- trust a repository
.PP
.SH SYNOPSIS
git annex trust \fB[repository ...]\fP
.PP
.SH DESCRIPTION
Records that a repository is trusted to not unexpectedly lose
content. Use with care.
.PP
Repositories can be specified using their remote name, their
description, or their UUID. To trust the current repository, use "here".
.PP
Before trusting a repository, consider this scenario. Repository A
is trusted and B is not; both contain the same content. \fBgit-annex drop\fP
is run on repository A, which checks that B still contains the content,
and so the drop proceeds. Then \fBgit-annex drop\fP is run on repository B,
which trusts A to still contain the content, so the drop succeeds. Now
the content has been lost.
.PP
.SH OPTIONS
.IP "The git-annex\-common\-options(1) can be used."
.IP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-semitrust(1)
.PP
git-annex\-untrust(1)
.PP
git-annex\-dead(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

