.TH git-annex-transferrer 1
.SH NAME
git-annex-transferrer \- transfers content
.PP
.SH SYNOPSIS
git annex transferrer
.PP
.SH DESCRIPTION
This plumbing\-level command is used to transfer data.
It is a long\-running process, which is fed instructions about
what to transfer using an internal stdio protocol, which is
intentionally not documented (as it may change at any time).
.PP
.SH OPTIONS
.IP "The git-annex\-common\-options(1) can be used."
.IP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

