.TH git-annex-rekey 1
.SH NAME
git-annex-rekey \- change keys used for files
.PP
.SH SYNOPSIS
git annex rekey \fB[file key ...]\fP
.PP
.SH DESCRIPTION
This plumbing\-level command is similar to migrate, but you specify
both the file, and the new key to use for it.
.PP
Multiple pairs of file and key can be given in a single command line.
.PP
Note that, unlike \fBgit-annex migrate\fP, this does not copy over metadata,
urls, and other such information from the old to the new key
.PP
.SH OPTIONS
.IP "\fB\-\-force\fP"
.IP
Allow rekeying of even files whose content is not currently available.
Use with caution.
.IP
.IP "\fB\-\-batch\fP"
Enables batch mode, in which lines are read from stdin.
Each line should contain the file, and the new key to use for that file,
separated by a single space.
.IP
.IP "\fB\-z\fP"
Makes the \fB\-\-batch\fP input be delimited by nulls instead of the usual
newlines.
.IP
.IP "Also the git-annex\-common\-options(1) can be used."
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-migrate(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

